// inmobiliaria (normalizada) -> KAM/owner. Generado de TARGETS (port de kam_map.py).

function norm(s: string): string {
    let t = String(s)
        .normalize('NFKD')
        .replace(/[̀-ͯ]/g, '')
        .toLowerCase()
        .trim();
    for (const ch of ['-', '.', ',', '&']) t = t.split(ch).join(' ');
    return t.split(/\s+/).filter(Boolean).join(' ');
}

const KAM_BY_NORM: Record<string, string> = {
    '1crea bienes raices': 'Sofia',
    '5a avenida real estate': 'Karen',
    'achavez asesores bienes raices': 'Ulises',
    'adama bienes raices': 'Sofia',
    'althia real estate': 'Ulises',
    'amika': 'Karen',
    'andina real estate': 'Laura',
    'arpa arquitectura y patrimonio': 'Karen',
    'arrendo properties': 'Sofia',
    'azteca realtors': 'Karen',
    'b b luxe': 'Karen',
    'bienes raices torillo': 'Ulises',
    'biens invest': 'Sofia',
    'bivo inmobiliaria': 'Ulises',
    'black brick real estate and investment': 'Karen',
    'bloco bienes raices': 'Sofia',
    'bos inmobiliaria': 'Sofia',
    'br23': 'Sofia',
    'broah espacios': 'Ulises',
    'brokeri inmobiliaria': 'Laura',
    'caralda promotora': 'Karen',
    'casa 7 real estate': 'Karen',
    'casane properties': 'Sofia',
    'cc vision patrimonial': 'Sofia',
    'cece': 'Karen',
    'centro inmobiliario': 'Karen',
    'circulo bienes raices': 'Karen',
    'cleverhaus soluciones inmobiliarias': 'Ulises',
    'cool living': 'Karen',
    'covein bienes raices': 'Sofia',
    'degohouse': 'Sofia',
    'diamond house': 'Sofia',
    'dream house inmobiliaria': 'Ulises',
    'enlace fehu': 'Ulises',
    'faro inmobiliaria': 'Ulises',
    'finver inmobiliairia': 'Ulises',
    'fortanza inmobiliaria': 'Sofia',
    'galdan realtors': 'Karen',
    'glad living': 'Laura',
    'glenview grupo inmobiliario': 'Ulises',
    'glomad': 'Laura',
    'finver inmobiliaria': 'Ulises',
    'zgm consultores inmobiliarios': 'Ulises',
    'inmobiliairia zam': 'Ulises',
    'godelta': 'Ulises',
    'green properties': 'Karen',
    'grupo ag bienes raices': 'Ulises',
    'grupo morada': 'Sofia',
    'habitanza': 'Sofia',
    'habitare luxury living': 'Laura',
    'habitax': 'Ulises',
    'habix grupo inmobiliario': 'Ulises',
    'harza real estate': 'Laura',
    'haz inmobiliaria': 'Laura',
    'henko bienes raices': 'Sofia',
    'hipoo mx': 'Sofia',
    'home community': 'Karen',
    'home investments': 'Pilar',
    'hs real estate': 'Sofia',
    'hsvision': 'Ulises',
    'humus grupo inmobiliario': 'Karen',
    'ielement inmobiliaria': 'Laura',
    'imagine inmobiliaria': 'Ulises',
    'inmo24': 'Karen',
    'inmoalianza bienes raices': 'Laura',
    'inmobiliaria 24siete': 'Sofia',
    'inmobiliaria broker premium': 'Karen',
    'inmobiliaria zam ai': 'Ulises',
    'inmonova inmobiliaria': 'Sofia',
    'inmoshop': 'Sofia',
    'inmovi': 'Ulises',
    'inmuebles proyecta': 'Ulises',
    'kaax real estate': 'Karen',
    'keeper propiedades': 'Ulises',
    'key finder inmobiliaria': 'Sofia',
    'kmi': 'Karen',
    'la inmobiliaria': 'Sofia',
    'lumina real state': 'Sofia',
    'luxurium realty': 'Sofia',
    'macvende s a de c v': 'Ulises',
    'malgram international': 'Sofia',
    'map bienes raices': 'Karen',
    'marube bienes raices': 'Ulises',
    'match inmobiliario': 'Karen',
    'mel inmobiliaria': 'Karen',
    'mercatecnia': 'Karen',
    'mm vitanova': 'Sofia',
    'monolitica real estate': 'Karen',
    'monroy properties real estate': 'Sofia',
    'moobi': 'Karen',
    'mood inmobiliario': 'Karen',
    'morare': 'Karen',
    'mv21 grupo inmobiliario': 'Karen',
    'new door': 'Karen',
    'nura': 'Ulises',
    'octavia': 'Ulises',
    'ok rentemos': 'Ulises',
    'opcion inmobiliaria': 'Karen',
    'oras bienes raices': 'Ulises',
    'orsa inmobiliaria': 'Sofia',
    'ov bienes raices': 'Ulises',
    'paquebeas2home': 'Sofia',
    'ponton asesores': 'Laura',
    'portalto inmobiliairia': 'Ulises',
    'professo bienes raices': 'Ulises',
    'pronoia real estate': 'Ulises',
    'property match': 'Sofia',
    'proyecto': 'Karen',
    'q inmobiliaria': 'Ulises',
    'quatre bienes raices': 'Sofia',
    'reset living': 'Laura',
    'ricoy bienes raices': 'Laura',
    'rocha inmobiliaria': 'Laura',
    'rubi inmobiliaria': 'Sofia',
    'scala hauss': 'Ulises',
    'seeker studio real estate': 'Karen',
    'senso real estate': 'Pilar',
    'soso inmobiliaria': 'Laura',
    'ss propiedades': 'Karen',
    't ubika real estate': 'Sofia',
    'talavera real estate': 'Sofia',
    'terraprop': 'Sofia',
    'todo en bienes raices': 'Karen',
    'top ten property': 'Ulises',
    'tukasa bienes raices': 'Laura',
    'turesi': 'Karen',
    'valentinos home sa de cv': 'Sofia',
    'vamos a vender': 'Sofia',
    'vive bien inmobiliaria': 'Karen',
    'vive capital br': 'Karen',
    'vive chic real estate': 'Karen',
    'we book realty': 'Karen',
    'wu realestate': 'Ulises',
    'zam inmobiliaria': 'Karen',
    'zgm': 'Ulises'
};

export function getKam(nombre?: string | null): string {
    if (!nombre) return 'Sin KAM';
    return KAM_BY_NORM[norm(nombre)] || 'Sin KAM';
}

// Cuentas dadas de baja. Se mantiene a mano: la baja es comercial y NO se refleja en Mongo
// (siguen con status 'active', inventario publicado y leads entrando), así que ninguna señal
// de datos las distingue. Agregar aquí conforme se den de baja.
const BAJAS = new Set<string>([
    'habix grupo inmobiliario'
]);

export function esBaja(nombre?: string | null): boolean {
    return !!nombre && BAJAS.has(norm(nombre));
}
