// Orden CANÓNICO de las 102 inmobiliarias (copia de `Análisis de Portales/.../_lista.txt`).
// Toda tabla por inmobiliaria va en ESTE orden, nunca alfabético: Ale pega las tablas en su Excel
// de trabajo, que ya tiene este orden fijo. Las que no estén aquí van al final, marcadas.
// Columnas: nombre · KAM · ¿se quedan? · tier. Si cambia la lista allá, se re-copia aquí.
export interface InmoCanon { nombre: string; kam: string; seQueda: boolean; tier: string }
export const ORDEN_INMOBILIARIAS: InmoCanon[] = [
    { nombre: "Diamond House", kam: "Sofia", seQueda: true, tier: "TOP" },
    { nombre: "Andina Real Estate", kam: "Laura", seQueda: true, tier: "TOP" },
    { nombre: "iElement inmobiliaria", kam: "Laura", seQueda: true, tier: "TOP" },
    { nombre: "Haz Inmobiliaria", kam: "Laura", seQueda: true, tier: "TOP" },
    { nombre: "Degohouse", kam: "Sofia", seQueda: true, tier: "TOP" },
    { nombre: "Ponton Asesores", kam: "Laura", seQueda: true, tier: "TOP" },
    { nombre: "HUMUS GRUPO INMOBILIARIO", kam: "Karen", seQueda: true, tier: "MID" },
    { nombre: "Casane Properties", kam: "Sofia", seQueda: true, tier: "TOP" },
    { nombre: "Inmobiliaria 24Siete", kam: "Sofia", seQueda: true, tier: "TOP" },
    { nombre: "Arpa - Arquitectura y Patrimonio", kam: "Karen", seQueda: true, tier: "TOP" },
    { nombre: "Reset Living", kam: "Laura", seQueda: true, tier: "TOP" },
    { nombre: "Bloco Bienes Raices", kam: "Sofia", seQueda: true, tier: "MID" },
    { nombre: "SOSO INMOBILIARIA", kam: "Laura", seQueda: true, tier: "TOP" },
    { nombre: "1Crea Bienes Raices", kam: "Sofia", seQueda: true, tier: "TOP" },
    { nombre: "Rocha Inmobiliaria", kam: "Laura", seQueda: true, tier: "TOP" },
    { nombre: "BOS Inmobiliaria", kam: "Sofia", seQueda: true, tier: "TOP" },
    { nombre: "Fortanza Inmobiliaria", kam: "Sofia", seQueda: true, tier: "TOP" },
    { nombre: "Arrendo Properties", kam: "Sofia", seQueda: true, tier: "MID" },
    { nombre: "Hipoo.mx", kam: "Sofia", seQueda: true, tier: "MID" },
    { nombre: "Covein Bienes Raices", kam: "Sofia", seQueda: true, tier: "TOP" },
    { nombre: "Ricoy Bienes Raíces", kam: "Laura", seQueda: true, tier: "TOP" },
    { nombre: "Caralda Promotora", kam: "Karen", seQueda: true, tier: "MID" },
    { nombre: "Proyecto", kam: "Karen", seQueda: true, tier: "MID" },
    { nombre: "Habitare Luxury Living", kam: "Laura", seQueda: true, tier: "MID" },
    { nombre: "Habitanza", kam: "Sofia", seQueda: true, tier: "MID" },
    { nombre: "Rubí Inmobiliaria", kam: "Sofia", seQueda: false, tier: "BOTTOM" },
    { nombre: "Vive Capital BR", kam: "Laura", seQueda: true, tier: "MID" },
    { nombre: "Talavera Real Estate", kam: "Sofia", seQueda: true, tier: "MID" },
    { nombre: "Vamos a Vender", kam: "Sofia", seQueda: true, tier: "MID" },
    { nombre: "Mercatecnia", kam: "Karen", seQueda: true, tier: "MID" },
    { nombre: "Quatre Bienes Raices", kam: "Sofia", seQueda: true, tier: "MID" },
    { nombre: "Property Match", kam: "Sofia", seQueda: true, tier: "MID" },
    { nombre: "Casa 7 Real Estate", kam: "Karen", seQueda: true, tier: "MID" },
    { nombre: "Monroy Properties Real Estate", kam: "Sofia", seQueda: true, tier: "MID" },
    { nombre: "Althia Real Estate", kam: "Sofia", seQueda: false, tier: "MID" },
    { nombre: "Luxurium Realty", kam: "Sofia", seQueda: true, tier: "MID" },
    { nombre: "Todo en Bienes Raices", kam: "Karen", seQueda: true, tier: "MID" },
    { nombre: "VALENTINOS HOME SA DE CV", kam: "Karen", seQueda: true, tier: "MID" },
    { nombre: "OV Bienes Raices", kam: "Laura", seQueda: true, tier: "MID" },
    { nombre: "Q Inmobiliaria", kam: "Laura", seQueda: true, tier: "MID" },
    { nombre: "ORSA inmobiliaria", kam: "Sofia", seQueda: true, tier: "MID" },
    { nombre: "Habix Grupo Inmobiliario", kam: "Laura", seQueda: false, tier: "Baja" },
    { nombre: "Opcion Inmobiliaria", kam: "Karen", seQueda: true, tier: "MID" },
    { nombre: "Finver Inmobiliaria", kam: "Laura", seQueda: true, tier: "BOTTOM" },
    { nombre: "Zam Inmobiliaria", kam: "Karen", seQueda: false, tier: "Baja" },
    { nombre: "Morare", kam: "Karen", seQueda: true, tier: "MID" },
    { nombre: "Enlace Fehu", kam: "Laura", seQueda: true, tier: "BOTTOM" },
    { nombre: "INMONOVA INMOBILIARIA", kam: "Sofia", seQueda: true, tier: "MID" },
    { nombre: "Scala Hauss", kam: "Laura", seQueda: true, tier: "MID" },
    { nombre: "Adamá Bienes Raíces", kam: "Sofia", seQueda: false, tier: "BOTTOM" },
    { nombre: "B&B LUXE", kam: "Karen", seQueda: true, tier: "MID" },
    { nombre: "GLENVIEW GRUPO INMOBILIARIO", kam: "Karen", seQueda: true, tier: "MID" },
    { nombre: "ZGM Consultores Inmobiliarios", kam: "Laura", seQueda: true, tier: "MID" },
    { nombre: "Match inmobiliario", kam: "Karen", seQueda: true, tier: "MID" },
    { nombre: "GoDelta", kam: "Laura", seQueda: true, tier: "BOTTOM" },
    { nombre: "KEEPER PROPIEDADES", kam: "Laura", seQueda: true, tier: "BOTTOM" },
    { nombre: "Octavia", kam: "Sofia", seQueda: true, tier: "MID" },
    { nombre: "WU REALESTATE", kam: "Karen", seQueda: true, tier: "MID" },
    { nombre: "Faro Inmobiliaria", kam: "Karen", seQueda: true, tier: "MID" },
    { nombre: "INMOShop", kam: "Sofia", seQueda: false, tier: "BOTTOM" },
    { nombre: "PROFESSO BIENES RAICES", kam: "Karen", seQueda: true, tier: "MID" },
    { nombre: "PRONOIA REAL ESTATE", kam: "Karen", seQueda: true, tier: "MID" },
    { nombre: "We Book Realty", kam: "Laura", seQueda: false, tier: "BOTTOM" },
    { nombre: "MOOBI", kam: "Karen", seQueda: true, tier: "MID" },
    { nombre: "Inmo24", kam: "Karen", seQueda: true, tier: "MID" },
    { nombre: "Mel Inmobiliaria", kam: "Karen", seQueda: true, tier: "BOTTOM" },
    { nombre: "HsVision", kam: "Laura", seQueda: false, tier: "BOTTOM" },
    { nombre: "KMI", kam: "Karen", seQueda: true, tier: "BOTTOM" },
    { nombre: "Green Properties", kam: "Karen", seQueda: true, tier: "BOTTOM" },
    { nombre: "Vive Chic Real Estate", kam: "Karen", seQueda: true, tier: "BOTTOM" },
    { nombre: "GLOMAD", kam: "Laura", seQueda: true, tier: "BOTTOM" },
    { nombre: "HS Real Estate", kam: "Sofia", seQueda: true, tier: "BOTTOM" },
    { nombre: "SS Propiedades", kam: "Karen", seQueda: true, tier: "BOTTOM" },
    { nombre: "5a Avenida Real Estate", kam: "Laura", seQueda: true, tier: "BOTTOM" },
    { nombre: "Kaax Real Estate", kam: "Laura", seQueda: true, tier: "BOTTOM" },
    { nombre: "Dream House Inmobiliaria", kam: "Karen", seQueda: false, tier: "BOTTOM" },
    { nombre: "Malgram International", kam: "Sofia", seQueda: true, tier: "BOTTOM" },
    { nombre: "Cece", kam: "Laura", seQueda: true, tier: "BOTTOM" },
    { nombre: "CC Vision Patrimonial", kam: "Sofia", seQueda: true, tier: "BOTTOM" },
    { nombre: "MM Vitanova", kam: "Sofia", seQueda: true, tier: "BOTTOM" },
    { nombre: "Mood inmobiliario", kam: "Laura", seQueda: true, tier: "MID" },
    { nombre: "Oras Bienes Raices", kam: "Laura", seQueda: true, tier: "MID" },
    { nombre: "Monolítica Real Estate", kam: "Karen", seQueda: true, tier: "BOTTOM" },
    { nombre: "T-Ubika Real Estate", kam: "Sofia", seQueda: true, tier: "BOTTOM" },
    { nombre: "CENTRO INMOBILIARIO", kam: "Laura", seQueda: true, tier: "BOTTOM" },
    { nombre: "LA INMOBILIARIA", kam: "Sofia", seQueda: true, tier: "BOTTOM" },
    { nombre: "Seeker Studio Real Estate", kam: "Karen", seQueda: true, tier: "BOTTOM" },
    { nombre: "INMOVI", kam: "Laura", seQueda: true, tier: "BOTTOM" },
    { nombre: "Harza Real Estate", kam: "Laura", seQueda: true, tier: "BOTTOM" },
    { nombre: "Black Brick Real Estate and Investment", kam: "Karen", seQueda: true, tier: "BOTTOM" },
    { nombre: "NURA", kam: "Sofia", seQueda: true, tier: "MID" },
    { nombre: "Broah Espacios", kam: "Laura", seQueda: true, tier: "BOTTOM" },
    { nombre: "9 Square Real Estate", kam: "Karen", seQueda: true, tier: "MID" },
    { nombre: "Aramil", kam: "Karen", seQueda: true, tier: "MID" },
    { nombre: "Cofuco Bienes Raíces", kam: "Karen", seQueda: false, tier: "BOTTOM" },
    { nombre: "DISRUPCION URBANA", kam: "Karen", seQueda: true, tier: "MID" },
    { nombre: "Grupo Ada", kam: "Karen", seQueda: true, tier: "MID" },
    { nombre: "Grupo JAHV", kam: "Karen", seQueda: true, tier: "MID" },
    { nombre: "Inin Capital", kam: "Karen", seQueda: true, tier: "MID" },
    { nombre: "Servicios inmoiliarios integrales", kam: "Karen", seQueda: true, tier: "MID" },
    { nombre: "Sinergia Asesores", kam: "Karen", seQueda: true, tier: "MID" },
    { nombre: "The Property Hub", kam: "Karen", seQueda: true, tier: "MID" },
];

/** Normaliza para comparar nombres de `companies.name` contra la lista (acentos, mayúsculas, signos). */
export const normInmo = (s: unknown): string =>
    String(s ?? '').normalize('NFD').replace(/[\u0300-\u036f]/g, '').toLowerCase().replace(/[^a-z0-9]+/g, '');

/**
 * Nombre de la lista → nombre(s) con que la cuenta existe en `companies`, cuando no coinciden.
 * Sólo los confirmados; los que no se encontraron se quedan sin alias y salen en cero con nota
 * (ver `SIN_CUENTA`), en vez de adivinar entre cuentas parecidas.
 */
export const ALIAS_INMO: Record<string, string[]> = {
    Aramil: ['Aramil Inmobiliaria'],
};
/** De la lista, sin cuenta identificable en Pulppo (30-sep-2026). */
export const SIN_CUENTA = new Set(['Grupo Ada', 'Servicios inmoiliarios integrales']);
